version: '3.8'

services:
  db-ccemuc:
    container_name: db-ccemuc
    image: postgres:13
    volumes:
      - pgdata_ccemuc:/var/lib/postgresql/data
    env_file:
      - ./env/db-ccemuc.env
    ports:
      - "5432:5432"
    networks:
      - ccemuc-network

  ccemuc-api:
    image: public.ecr.aws/g3j2f9k6/ccemuc-api:latest
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    env_file:
      - ./env/ccemuc-api.env
    depends_on:
      - db-ccemuc
    networks:
      - ccemuc-network


networks:
  ccemuc-network:
    driver: bridge

volumes:
  pgdata_ccemuc:
  red_data: {}
