# We use alpine for a lightweight (less memory) image
FROM node:16-alpine

# Create app directory
WORKDIR /ccemuc-api

# Copy the files that declares the dependencies (in this case using yarn)
COPY package.json ./
COPY package-lock.json ./
# COPY run-migrations-script.js /stocks-api/run-migrations-script.js

# Install the dependencies
RUN npm install

# Copy all the files into the container to run the app
COPY . .

# Cambiar permisos de ejecución
RUN chmod +x /ccemuc-api/start.sh
# RUN chmod +x /ccemuc-api/run-migrations.sh

# Run command to start the process runing a shell command using node
ENTRYPOINT [ "./start.sh" ]

# This is for documentation only, the port muyst be exposed manually or in compose definition.
EXPOSE 3000
